### PR TITLE
Fix Python dependencies

### PR DESCRIPTION
**Pull request by giorgiosironi**
The image stopped building because:
- `django` `2.1.6` vanished from PyPI due to a [packaging
error](https://docs.djangoproject.com/en/2.1/releases/2.1.7/)
- `psycopg2` fails compilation in many situations, so just use a binary
package like normal people do

### CODE REVIEW

**Comment by giorgiosironi** [comment]
The image now builds, but the result fails the tests. Why?

**Comment by lsh-0** [comment]
I'll take a closer look at this for you today

**Comment by lsh-0** [comment]
I can replicate this locally without all the docker + pipenv crap. Investigating

**Comment by lsh-0** [comment]
The problem probably lies with the major version bump to `jsonschema` here: https://github.com/elifesciences/digests/pull/32/files#diff-46bb8405eeb4d8a11deb635f562f7c48R105

The `jsonschema` changelog says it's introduced Draft7 support with the 3.0 release: https://github.com/Julian/jsonschema/blob/master/CHANGELOG.rst

and also mentions a new 'TypeChecker' that sounds suspicious. After some debugging I can see that the expected error still exists, but a more specific error is being returned:
```
{'cause': None,
 'context': [],
 'instance': {'foo': 'bar'},
 'message': "'type' is a required property",
 'parent': <ValidationError: "{'foo': 'bar'} is not valid under any of the given schemas">,
 'path': deque([]),
 'relative_path': deque([]),
 'relative_schema_path': deque([0, 'required']),
 'schema': {'$schema': 'http://json-schema.org/draft-04/schema#',
            'properties': {'text': {'title': 'Text', 'type': 'string'},
                           'type': {'enum': ['button'], 'type': 'string'},
                           'uri': {'format': 'uri',
                                   'title': 'URI',
                                   'type': 'string'}},
            'required': ['type', 'text', 'uri'],
            'title': 'Button',
            'type': 'object'},
 'schema_path': deque([0, 'required']),
 'validator': 'required',
 'validator_value': ['type', 'text', 'uri']}
```

This "`{'foo': 'bar'}`" is what is being injected into the data and POSTed and failing validation. The rest of the data is quite large and (presumably) valid. 

The intent of the test seems to be to ensure invalid content generates a 400 (Bad Request), the error message is a side effect. 

I'll update the message and get this build green, but I have a few other tweaks that will let us debug this locally without all the Docker/pipenv cruft

**Comment by lsh-0** [comment]
> I have a few other tweaks that will let us debug this locally without all the Docker/pipenv cruft

oh, I see pipenv is really integrated everywhere :(  what a mess. I'll commit what I have for posterity

**Pull request merged**
