### PR TITLE
bumps version of Django to 2.1.5

### PR DESCRIPTION
**Pull request by lsh-0**
another pipenv project

used two separate commands this time, `pipenv lock` after updating `Pipefile`, but that affected heaps of things, and then `pipenv update django` as recommended here: https://pipenv.readthedocs.io/en/latest/basics/#example-pipenv-upgrade-workflow but same deal. I thought these must have been Django dependencies, but pytest and freezegun et al are in there, so I give up.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
> pipenv lock after updating Pipfile

I could never make that work; I think the only solution is to pin what you don't want to be updated in `Pipfile`.

**Comment by lsh-0** [comment]
please merge this if you guys are happy

**Comment by lsh-0** [comment]
... or I could just tear pipenv out. maybe in another PR

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/issues/issues/4696

**Pull request merged**
